
version: '3.8'

services:
  audiobookbay-downloader:
    image: ghcr.io/jamesry96/audiobookbay-automated:latest
    ports:
    - "5078:5078"
    container_name: audiobookbay-downloader
    environment:
    - DOWNLOAD_CLIENT=qbittorrent
    - DL_SCHEME=http
    - DL_HOST=192.168.1.66
    - DL_PORT=8080
    - DL_USERNAME=admin
    - DL_PASSWORD=pass
    - DL_CATEGORY=abb-downloader
    - SAVE_PATH_BASE=/audiobooks
    - ABB_HOSTNAME='audiobookbay.is' #Default
  restart: unless-stopped

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - WEBUI_PORT=8080
    - TORRENTING_PORT=6881
    volumes:
    - ./config:/config
    - ./downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
  restart: unless-stopped