
version: '3.8'

services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=protonvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY= #[enter your Private Key Here]
      #- SERVER_COUNTRIES=US
    ports:
     # - "8082:8080" # qbittorrent WebUI
      - "8009:8000/tcp"
      - "6081:6881"
      - "6081:6881/udp"
      - "6011:6011"
      - "6012:6012"
      - "8084:8084" #CAWD port
      - "5078:5078" #audiobookbay downloader port

  audiobookbay-downloader:
    image: ghcr.io/jamesry96/audiobookbay-automated:latest
    ports:
    - "5078:5078"
    container_name: audiobookbay-downloader
    environment:
    - DOWNLOAD_CLIENT=qbittorrent
    - DL_SCHEME=http
    - DL_HOST=192.168.1.66
    - DL_PORT=8080
    - DL_USERNAME=admin
    - DL_PASSWORD=administrator
    - DL_CATEGORY=abb-downloader
    - SAVE_PATH_BASE=/audiobooks
    - ABB_HOSTNAME= 'theaudiobookbay.se' #'audiobookbay.is' #Default
    restart: unless-stopped
#    network_mode: "service:gluetun"

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - WEBUI_PORT=8080
    - TORRENTING_PORT=6881
    volumes:
    - ./config:/config
    - ./downloads:/downloads
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
#    network_mode: "service:gluetun"